### ISSUE TITLE
Render of private organization teams on public organization page causes crash

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/osm-teams#351]
### Problem
The YouthMappers organization page is failing. Page crashes with error `Application error: a client-side exception has occurred (see the browser console for more information).`

```
TypeError: a.map is not a function
    at T.renderOrgTeams ([id]-f2c17e1f3fe23fa9.js:1:3843)
    at T.render ([id]-f2c17e1f3fe23fa9.js:1:8867)
    at uh (framework-2fe4cb6473b20297.js:9:75833)
```

I believe that the renderOrgTeams() method introduced in #329 is causing organization pages to fail when a user does not have the proper access to view the teams associated with an organization. 

Additionally, the YouthMappers organization is private. As a non-member, I should not be able to view this page.

### Solution:
The application should not render any private teams in the organization teams list on a public organization page.

**Comment by LanesGood** [comment]
This is no longer present. Users instead see an "Unauthorized" page - we'll explore fixing this in #428
